name: make_n8n
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip>=23.0
  - pip:
    - crewai>=0.5.0
    - perplexityai>=1.0.5
    - requests>=2.31.0
    - pydantic>=2.4.2
    - tenacity>=8.1.0
    - langchain>=0.1.0
    - langchain-openai>=0.0.2
    - openai>=1.7.1
    - tiktoken>=0.5.2 